#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Kanata\TheGrid\Commands\StartTheGridCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new StartTheGridCommand);

$application->run();
